language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "iojs"
before_install:
  - echo "travis before_install"
intall:
  - npm install

before_script:
  - npm run ng test

script:
  - npm run ng build
