sudo: required
env:
  global:
# SONAR_GITHUB_TOKEN
  - secure: "co7HHM5Za4yxIkK5sO1+HXmD4+bFlg7EehXzAA9fl8+jcrrnitELUcXr7blqIJta+e8jJAoBzHwj4gCN9y4FcZd5RkrAV87imN7tvZO1SagEO07x3YzESasKT7avL9otzmWrkIMQP8+CD4Sl71gPfJ4RmMxouVMPOQLNdSNDA401klh/8nFPbDxsIWvCq1FoKCm3owYW7GJk22t0LowfJQvCcc6IUyjVHskWq/s+2JeS7PlEVFM+qiyXUKk2M5r+war6aZZoI0crp5jgpNZf4xMI+Od02oCYbhPqmwSwOVocf0849od2yAfT8fIpcvl1zGbaxBj74IFAHpY3UX4gHJUZfBBBAm7dhyq0ESseKaxhGU5LlOMnzsOl1rPkNrU04oYF3PD+itrIBQq1KxmxosTazlV1NK59i7hqSg7YHu4C6g0aBbcavY42s7i+S5YOhG6iinp5DZ4rheWlHmnaBM2R9LiXDtqK2I4P2kbdxGdWvBHkjomoUD02zJm7rhC7NFqcgT3BaLpuWmgueXngB6e2TxGgyC36zT8bUIfm7cxPuCwJY+05/ZuoFxZPg/UPFpPpU1aCKDaNho0R6CR3LdsZRk9yOX2DOi8R2wljSZZ9xRWpiJXqVWArnA0aLeImxXVoT6kV0LpFsRtadlZUSmEaR5d9H4JUrGSCv0jwu+Q="
# GITHUB_TOKEN
  - secure: "X1Y4WWDx09OD/OEiX4nvCZEKjEl/DgfVeaz10KSmbPOP5VNF76RmZAtOrGp3ODUJiLlLO/Hgr3BSSvhcc5RAiqUzKlZ2bofLFDzufRXVwfgVmEJyHsEpp80La8MxQsvWXC0zTtfuu0PEQkv3jLrT7A6NQvgeYjKlBdz3TaDdpAUUBlBn470fg7bkrgpdisUu9saOwpcy0MeoB3myloEyRnJXHs7k1RLDF8sSFo36GYe8vEZInTj6vJCKquZiWuvSGocjbFA8ft5Ko6nUS+QrnXtj3xcAABxQ+Q1I/3PC1NAH0tYjubXdu16VAqhvjBfILH64NUf9XDlRr9ZJNewSUGW1MHhyldbW0AQOvBWaGST+AgFhRHD6chODxDe5x2qfabi9DwTrB97QI4TGEUzn69k06uJex79etdsqtI9rB//pHsT0SNxz5JtuICwjbcHWMyjU41K5tp63p7VXp8+bKUtM4Ea7uzJfkaWUck7CC3++13f5UyK4Wwao7N1hlmd1kzcR20a3ypOoIDMArZNJhr+pWIdIow3oAgLPOzooDbUoYCLhA2pJ8Kb1a4HFHxPd9nw4AoNI+Hj3/9iKZodV9tP3Hw7PEZ5ShZjV7aF2Af4NoSCIUz+ecJJejeXuXU1G0r/En5GGKp8dFinZjZRmgyN+A8D/nZ6M789L8s6JvIU="
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
addons:
  sonarqube:
    branches:
    - master
    - devel
language: node_js
node_js:
- "node"
- "lts/*"
- "8"
- "7"
- "6"
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
intall:
- npm install
before_script:
- npm run build
script:
- npm start &
- sleep 10
- npm run e2e

after_script:
- sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82
