sudo: required
env:
  global:
# SONAR_GITHUB_TOKEN
  - secure: "fpIMC9EWQa+Q4W5Vu74Yc5RCp1sa+dNbEX2ZsxyzlDBztjJ3VbnuHKfjHQs/iUkNI7ED349WRrQCCjz7gymQ0occEOtMzBSBfruty2SjsNEPffp3Vl0Fid6AazmZImH+09Juaibgb/tugVH93C0VDiEauFwIYuofYv12T0GxAeHHWvBj7IcwgY2AGUvE/ulW27m5rXly4RLlWwpUSvd8eSYHPCqCmH/rIJzPT0QMMMrjcWrl3zDLjcMwhp1wnJYMPk+DL/9a+sKJXOVaVMXF6jkKUouOdA6aBfjW/v1IRKivS+IfMNiENE/CNrJLdE4xwTuolh50/AzZlDpIgYPJlfK6B+w8oBr09NG+zrQLHYEwVL6E8/ZvIPNh6NjArrJLgasAmn6ZLPemXMRhPjQIlN5ougLGFN883Oy5yxGH/uXmxCtyZGK0EwyU7NzLzIrTEAYZIXF5P+bJDUy4AyGeWjmbFAe5zUkvUgTpW7CLJ2gKTyiZuS7BpgShsBknvUUB96uAig469Ayr+O0inhyfxskWDnMOduo/ouH3O16k6EF7PSopqtHlbpn+u2bKKesv80iVrM21WM4qh5Y9cordw4HcflA71rfUZCOUnzeIgE/k0Dk4Md9LCN6cgj0FxlLgYkBCDqm1d/Ou+GOEKvNqR5QjI0pBooYR9WpdxdCEHz0="
# GITHUB_TOKEN
  - secure: TODO_GITHUB_TOKEN
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
addons:
  sonarqube:
    branches:
    - master
    - devel
language: node_js
node_js:
- "node"
- "lts/*"
- "8"
- "7"
- "6"
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
intall:
- npm install
before_script:
- npm run build
script:
- npm start &
- sleep 10
- npm run e2e

after_script:
- sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82
