sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - echo "travis before_install"
intall:
  - npm install

before_script:
  - npm run ng test

script:
  - npm run ng build
