build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"
platform:
  - x86
  - x64
install:
  - "npm install"
before_test:
  - "npm run build"
test_script:
  - "npm run test"
  - echo "BUILD SUCCESS"
