branches:
  only:
    - master
    - devel
environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
platform:
  - x86
  - x64
before_install:
  - "npm install -g angular-cli"
install:
  - "npm install"
before_test:
  - "npm run build"
test_script:
  - "npm run e2e"
