build: off
branches:
  only:
    - master
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - npm install

before_test:
  - npm run ng build

test_script:
  - echo "BUILD SUCCESS"
