build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
platform:
  - x86
  - x64
build_script:
  - "node -v"
  - "npm -v"
  - "npm install"
before_test:
  - "npm run build"
test_script:
  - "npm run e2e"
