build: off
branches:
  only:
    - master
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - npm install

before_test:
  - npm run pree2e
  - npm run ng serve& 
  - sleep 30
  - npm run e2e

test_script:
  - npm run ng build
  - echo "BUILD SUCCESS"
