build: off
branches:
  only:
    - master
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    allow_failures:
      - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

before_test:
  - npm run ng build

test_script:
  - npm run ng test
