# NodeJS CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 57ba32cda619d90224450266ffc417b3f8bb6fb1ef7d1ccb28b365060298c19a
    docker:
      - image: circleci/node:8.11.3-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # CI, CircleCI dependencies
            # CI, codeclimate dependencies
            npm install -g codeclimate-test-reporter
      - run:
          name: Pre-Install project
          command: |
            rm -rf node_modules/
      - run:
          name: Install project
          command: |
            npm install
      - run:
          name: Before Tests
          command: |
            ./cc-test-reporter before-build
      - run:
          name: Run Tests
          command: |
            npm test
      - run:
          name: After Tests
          command: |
            npm run lint:html
            npm run lint:xml
            # CODECLIMATE_REPO_TOKEN=$CC_TEST_REPORTER_ID codeclimate-test-reporter < tests/reports/coverage-lcov.info
      - store_artifacts:
          path: dist
          destination: dist
